verbose: True
seed: 42
model_type: "sfno"
nepochs: 1

sfno:
  emded_dim: 64
  num_layers: 4

paths:
  input_dir: "/scratch4/GFDL/gfdlscr/Uriel.Ramirez/archive_260429/ANEMOI-DATASETS/Set3"
  training: "train_dataset.zarr"
  validating: "val_dataset.zarr"
  testing: "test_dataset.zarr"

batch_size: 16
precision: "bf16-mixed"

data_config:
  type: "residual"     # "default" or "residual"
  method:
    name: "autoregressive"      # "lags" or "autoregressive"
    nsteps: 3

use_coordinates: False

variables:
  air_temperature_at_two_meters:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"

  eastward_wind:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    vertical_levels: [25, 96, 203, 345, 517, 695, 847, 963]

  northward_wind:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    vertical_levels: [25, 96, 203, 345, 517, 695, 847, 963]

  specific_humidity:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    vertical_levels: [25, 96, 203, 345, 517, 695, 847, 963]

  air_temperature:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    vertical_levels: [25, 96, 203, 345, 517, 695, 847, 963]

  DLWRFsfc:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True

  DLWRFsfc:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True

  PRATEsfc:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True

  PRESsfc:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True

  SHTFLsfc:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True

  ULWRFsfc:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True
  
  ULWRFtoa:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True
  
  USWRFsfc:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True

  USWRFtoa:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True
  
  surface_evaporation_rate:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True
  
  surface_temperature:
    is_input: true
    is_output: true
    is_static: false
    target_weight: 1.0
    normalization: "z-score"
    diagnostic_only: True

  DSWRFtoa:
    is_input: true
    is_output: false
    is_static: false
    normalization: "z-score"

  HGTsfc:
    is_input: true
    is_output: false
    is_static: true
    normalization: "z-score"

  land_fraction:
    is_input: true
    is_output: false
    is_static: true
    normalization: "none"
